name: Upload to Tencent COS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ AKID41oQq45tY0GJArLcnlW5SdbMyiHdpsoc}}
          secret_key: ${{ fBYEtTuEOSN9mPtFTYXOcjkcLvOiuxse }}
          bucket: math-1378865866
          region: ap-beijing
          source: ./
          dest: /
